language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t alicewillbe/nba-web -f Dockerfile.dev .

scripts:
  # dummy CI

after_success:
  - docker build -t alicewillbe/nba-web .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alicewillbe/nba-web