language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t alicewillbe/nba-web -f Dockerfile.dev .

script:
  - docker run -e CI=true alicewillbe/nba-web npm run test

after_success:
  - docker build -t alicewillbe/nba-web .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push alicewillbe/nba-web