language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t indreklasn/my-react-docker-app -f Dockerfile.dev .

scripts:
  # dummy CI

after_success:
  - docker build -t indreklasn/my-react-docker-app .
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push indreklasn/my-react-docker-app