version: "3.8"
services:
  client:
    image: alicewillbe/nba_web_client:latest
    stdin_open: true
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - "./app/node_modules"
      - "./:/app"